events {}

http {
  server {
    listen 80;

    location /auth/ {
      proxy_pass http://host.docker.internal:8001;
    }

    location /groups/ {
      proxy_pass http://host.docker.internal:8002;
    }

    location /loans/ {
      proxy_pass http://host.docker.internal:8003;
    }
  }
}